# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# CSS 143B
# This file is for github grading

# DO NOT CHANGE IN FINAL SUBMISSION

name: css 143 grader

on:
  # Uncomment the following two line to run test when you push to master in your own branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, reopened, synchronize]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Check due date 
        run: bash .github/workflows/check_due_date.sh
      - name: Check no change to master branch 
        run: bash .github/workflows/check_no_change_to_master.sh


  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
